image:
- Visual Studio 2022
build: "off"
init:
- ps: |
    &$Env:ProgramFiles\Docker\Docker\DockerCli.exe -SwitchDaemon
- ps: |
    &$Env:ProgramFiles\Docker\Docker\DockerCli.exe -SwitchWindowsEngine
install:
- ps: docker images
- ps: |
    [System.Environment]::OSVersion.Version
    systeminfo.exe | sls Version
    winver
- ps: |
    (Measure-Command {docker pull mcr.microsoft.com/windows/servercore:ltsc2019}).TotalSeconds
