image:
- Visual Studio 2022
build: "off"
init:
- ps: |
    &$Env:ProgramFiles\Docker\Docker\DockerCli.exe -SwitchDaemon
- ps: |
    &$Env:ProgramFiles\Docker\Docker\DockerCli.exe -SwitchWindowsEngine
install:
- ps: docker images
- ps: Invoke-WebRequest -Uri http://ntfy.sh/monacelli-shelfhigh -Method POST -Body ready
